### ISSUE TITLE
Vote to decide Python support

### ISSUE THREAD

**Issue by bmcorser** [ipfs/py-ipfs#18]
:baby: ←#2
### @whyrusleeping
- [x] Don't support Python 2 at all
- [ ] Support to 2.7
### @BrendanBenshoof
- [x] Don't support Python 2 at all
- [ ] Support to 2.7
### @sirMackk
- [ ] Don't support Python 2 at all
- [ ] Support to 2.7
### @SilverWingedSeraph
- [x] Don't support Python 2 at all
- [ ] Support to 2.7
### @mvanveen
- [ ] Don't support Python 2 at all
- [ ] Support to 2.7
### @bmcorser
- [ ] Don't support Python 2 at all
- [x] Support to 2.7
### @julienpalard
- [x] Don't support Python 2 at all
- [ ] Support to 2.7

Not sure if there are any other stakeholders ...

**Comment by BrendanBenshoof** [comment]
The core of my argument is as follows:
- Stock python3 is the future arguments and we should incentivize moving to it
- If the primary use case of this was to be a library or programming interface, I could see an argument for python 2. (Our client package supports python 2 and 3 for this reason!) Our primary use case is a daemon style service, to be run in background or on a headless server.
- Expecting users to install python3 to use a standalone service is reasonable.
- The argument of "but lots of people still program python2" falls short because while the ability to hack on, re-use, and modify our code is nice, it is a much lower priority then developing and maintaining the code and supporting python 2 does not really provide much utility to those ends anyway.
- Supporting python2 requires effort we don't need to spend, and those efforts are a scare resource right now.

**Comment by whyrusleeping** [comment]
casting my vote against supporting python2, not because i like python3 (i personally hate python3, and i try to only ever use 2.7) but because supporting both becomes tricky and can cause confusion in places.

**Comment by NoraCodes** [comment]
I'd like to vote against supporting python2, not because I dislike programming in it but because it's unacceptable to not support python3 and a waste of time to support both.

**Comment by bmcorser** [comment]
That's a majority in favour of Python 3 only. Motion carried `:)`

**Comment by jbenet** [comment]
I don't think this is a representative sample. If the aim is to be democratic to the Python user base, base it on real deployment numbers. 

But If the aim is to be dev idiomatic, carry on. I suspect it wouldn't be impossible to isolate incompatibilities and address them later on.

—

**Comment by bmcorser** [comment]
Everyone who voted (apart from me!) voted not to support 2.7

This repo is actually configured to run tests against 2.7 using Tox on Travis, so we will see incompatibility there.

**Comment by amstocker** [comment]
not that it affects the vote at all, but if there is going to be any async i/o it would tough to span different versions of python, so it would probably best to choose one framework/version to work with at first (i'm inclined to say 3.4+ w/ asyncio, although I haven't used it much).

**Comment by Mec-iS** [comment]
same as @amstocker 
+1 only 3.4+

**Comment by candeira** [comment]
I´d even say 3.5+ or even a later one, not commit to a current 3.x version.

By the time py-ipfs is ready for non-developers to use, there might be a 3.7 with useful things. So why get married to 3.4? Better not pin a version for now, just target "cpython latest" while in development, decide to pin it down later.

I also vote to not go out of our way to support 2.7.

**Comment by Mec-iS** [comment]
@candeira Yeah, stuff like 3.5's "type hinting" or other future features built aside/on can become central for future versions, beside the already mentioned async/await interface. As you said, having the latest CPython is the thing for projects that look at the next decades.
However I was talking with @jgraef about the lack of latest protobuf2 support for Python3, I don't know if this could be a problem so I opened #25
Hope to join a sprint talk soon or later, I have just read the specs and paper yesterday.
