### ISSUE TITLE
Py-libp2p broken link.

### ISSUE THREAD

**Issue by alexfortin17** [ipfs/py-ipfs#36]
Hey everyone. I was just starting to look around because I want to contribute to this project. I read that an implementation of py-libp2p should be one of the first step but currently the link found in the roadmap is broken. 
As any work been done yet and if so where is it?

**Comment by ntninja** [comment]
Unfortunately you commented during a time when there was nobody with commit rights watching this project, hence the lack of response. Please see the more recent comments on #1 for an idea about the current status of this project.

The link you mentioned likely never worked because there never has been an implementation of `libp2p` in Python. I decided to simply remove to reflect this. Thanks for reporting this!
