### ISSUE TITLE
Using Morph.is code to improve IPFS

### ISSUE THREAD

**Issue by thearkadia** [ipfs/py-ipfs#37]
I'm cross-posting this from the Orbit github since Morphis is written completely in Python and is really similar to IPFS so it can help speed along the development of py-ipfs. 

The main developer was shot and killed 2 weeks ago and it would mean a lot for his work to live on. https://morph.is is a distributed datastore like IPFS and there was a ui being developed for a distributed irc\slack which you can get if you pull the source and git checkout f-dds (the idea was to have it be completely functional without any JavaScript for those who prefer the added security of not running any JavaScript, with optional settings and tools for those who don't mind JavaScript)

the distributed irc was almost done heres a mockup of what it was going to look like https://ipfs.pics/Qmab8KzU4jCEYwwHQaDRNBQGu2eRSf9Qvkhfjn7Q63qFTH
if you run a morphis node with the f-dds branch you can see and use most of it in action. There were some tweaks to the ui we had talked about but never got around to finish.

Heres a backup of the code including all branches (which is also currently still available on the official morph.is git repo until the servers go offline)

https://u.teknik.io/XWzPR.zip

**Comment by jangondol** [comment]
@arkgit That is truly horrible, so sorry to hear that. I saved the ZIP file for posterity ([archive.org](https://web.archive.org/web/20170103223649/https://u.teknik.io/XWzPR.zip)). Please note possible licensing issues (GPL v2 vs. MIT). Same applies to haadcode/orbit#218.

**Comment by ntninja** [comment]
While this is indeed a sad story, the licensing makes it impossible to use any parts of *morph.is* in `py-ipfs` unfortunately. As far as I'm concerned LGPL would have been fine too, but GPL requires all users of the library to be GPL too. For a general-prupose library (that `py-ipfs` will possibly one day become) that restriction is unacceptable and since the primary author is dead these terms and conditions will not be changed for the next ~70 years (until it becomes public domain).

Sorry about this, but that's how licensing works. :slightly_frowning_face:
